version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - docker --version
      - gradle --version
  post_build:
    commands:
      - echo Build completed on `date`
      - gradle build
artifacts:
  base-directory:
  files:
     - '**/*'
    # - build/libs/gradleproject-1.0.jar
